### ISSUE TITLE
libGetFrame hanging on combat end in dungeons

### ISSUE THREAD

**Issue by ryanschmitty** [mrbuds/LibGetFrame#10]
I used CPUThieves to catch the culprit that was hanging my game whenever we drop combat after a pack in M+ dungeons. It starts to happen after a dungeon or so, sometimes a little less, sometiems a little more, and the only thing that fixes it is a /reload, at which point it'll be fine until about a dungeon's worth of time again.

![Annotation 2020-05-26 125715](https://user-images.githubusercontent.com/656995/82944663-735e9580-9f50-11ea-839a-97d8fc0428b8.png)

[SavedVariables.zip](https://github.com/mrbuds/LibGetFrame/files/4684728/SavedVariables.zip)

Here's a link to my compressed addons folder (~115MB): https://drive.google.com/file/d/1WrsQ3aM9WUYBe5leP_I_Aj5pKhpgNJOM/view?usp=sharing

**Comment by mrbuds** [comment]
After installing your addons, i get a lot of elvui errors on load, it seems it's a old version, i have not checked for all your addons, but the issue with libgetframe could come from bugged old addons

**Comment by ryanschmitty** [comment]
Sorry, I forgot those were there: I have Elvui and it’s config disabled.

**Comment by mrbuds** [comment]
So you don't use any unitframe and nameplate addon ?

**Comment by mrbuds** [comment]
Issue identified to badly written clickable weakauras
https://wago.io/B1tDZFluX

I'll keep this issue open until i'v decided if i do something to mitigate this.

**Comment by ryanschmitty** [comment]
> So you don't use any unitframe and nameplate addon ?

Correct
