### ISSUE TITLE
Feature Request: Expose interface to get player unit frame directly

### ISSUE THREAD

**Issue by arnoldkao** [mrbuds/LibGetFrame#13]
Please add to the public interface a way to retrieve the player unit frame, even when the player is in a group. For example, add an `ignoreGroupFrame` option, or expose `defaultPlayerFrames` so I can plug that in as the value for `framePriorities`.

**Comment by mrbuds** [comment]
I added 2 new options
ignorePartyFrame : boolean (default false)
partyFrames: default
```Lua
{
    "^AleaUI_GroupHeader",
    "^SUFHeaderparty",
    "^ElvUF_PartyGroup",
    "^oUF_.-Party",
    "^PitBull4_Groups_Party",
    "^CompactParty",
}
```

**Comment by inkounter** [comment]
Thanks, but in my use case, I also want to ignore raid frames. It doesn't look like the new changes fully cover my need.

**Comment by mrbuds** [comment]
I added ignoreRaidFrame & raidFrames options too
