### ISSUE TITLE
Focus target taking priority over party frame dynamic group

### ISSUE THREAD

**Issue by Zyin055** [mrbuds/LibGetFrame#14]
This is a bug report I posted for WeakAuras and was told to repost it here. See the link for the full details: https://github.com/WeakAuras/WeakAuras2/issues/3143

> Not sure if this is working as intended, but when using "Group by Frame" and selecting "Unit Frames" for a dynamic group the auras apply to your focus target in addition to your party members. In Classic vanilla the focus target feature did not exist and it only applied to your party members.
> 
> Here's the real bug: the focus target appears to take priority over the party frame. For example, I have a weakaura to show when party members are drinking. I have the tank focused and it will show the focus frame drinking, but not his party frame.

**Comment by mrbuds** [comment]
Thanks for making this issue, i need to know which addons you are using for your foucs and party frames ?

**Comment by Zyin055** [comment]
[Luna Unit Frames](https://www.curseforge.com/wow/addons/lunaunitframes) for both.

**Comment by mrbuds** [comment]
Luna Unit Frames is not supported by LibGetFrame, see https://github.com/mrbuds/LibGetFrame/pull/12
