### ISSUE TITLE
Request to add more unitframes to libGetFrame

### ISSUE THREAD

**Issue by Woosuk1624** [mrbuds/LibGetFrame#24]
Dear expert,

Missing unit/raidframes in libGetFrame makes incorrect behavior of external glowing, pointing frametype to ‘unitframe’.

I have used ‘InvenRaidFrame3’ (former raidframe of Lime), and found it was missing in this library. Sometimes external glowing works into this frame but sometimes not.

It looks working with "^InvenRaidFrames3Group", --IRF3 in LibGetFrame-1.0.lua.

**Comment by Woosuk1624** [comment]
[InvenRaidFrame3.zip](https://github.com/mrbuds/LibGetFrame/files/8355539/InvenRaidFrame3.zip)
Inven Raid Fram3 : origin of Lime Raid Frame which is already registered in LibGetFrame

[InvenUnitFrame.zip](https://github.com/mrbuds/LibGetFrame/files/8355542/InvenUnitFrame.zip)
UnitFrame version of above RaidFrame.

**Comment by mrbuds** [comment]
fixed with https://github.com/mrbuds/LibGetFrame/commit/84e7a34b68346d6f23bf04a7555028d522e996f4
