### ISSUE TITLE
Raid frame glows of some WAs not appearing after update

### ISSUE THREAD

**Issue by wkrueger** [mrbuds/LibGetFrame#26]
Latest update (1.5.9) breaks weakauras that use raid frame glows.

Testing path:
- Have a weakaura that triggers glows (ex: Dibs on Power Infusion, Innervate me, etc)
- Create a custom group on group finder
- Whisper yourself the trigger word of the aura (ex: pi me, innervate, etc)

While the auras trigger, they don't show glows on the raid frame. When I disabled LibGetFrame the glows appeared again.

**Comment by mrbuds** [comment]
https://github.com/mrbuds/LibGetFrame/commit/730fd36878ebb94d4b37f309cc0228f719b60093 revert last change
