### ISSUE TITLE
Memory Spikes

### ISSUE THREAD

**Issue by burnep** [mrbuds/LibGetFrame#28]
Since minor version 42 (the introduction of coroutine), memory usage (and especially spikes) have gotten pretty severe. I've witnessed a 2 orders of magnitude increase between version 41 and 42 at the top end. This is a constant big spike->collection cycle.

I'm not sure if this is just a calculated side effect weighed against the benefits, but just thought I'd let you know.

**Comment by mrbuds** [comment]
How are you measuring this?

**Comment by burnep** [comment]
By running a couple addons that include LibGetFrame in a high unitframe environment (AV) with [AddonUsage](https://www.curseforge.com/wow/addons/addon-usage) also running. Then swapping in old versions of LGF with nothing else changed and seeing (sometimes significant) changes. One addon's memory increased 10-fold from ver 41 to 46 (I put an issue in with them as well).

idk much about all this, was just something I noticed and tried to track down the cause

**Comment by mrbuds** [comment]
It's normal that the lib use more memory while scanning, with coroutines it takes a few frames to finish build the table, so it has to do that in a temporary table to not have partial results during the scan.
It's a memory vs cpu tradeoff.
