### ISSUE TITLE
BugSack error

### ISSUE THREAD

**Issue by Milky063** [mrbuds/LibGetFrame#29]
Getting the following errors today just after doing a /reloadui command or just simply logging into the game...

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:2 Error loading Interface/AddOns/LibDFramework-1.0/Libs/LibStub/LibStub.lua

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:3 Error loading Interface/AddOns/LibDFramework-1.0/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:4 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/LibSharedMedia-3.0-8020003/lib.xml

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:5 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceGUI-3.0-41/AceGUI-3.0.xml

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:6 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceDBOptions-3.0-15/AceDBOptions-3.0.xml

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:7 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceLocale-3.0-6/AceLocale-3.0.xm

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:8 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceAddon-3.0-13/AceAddon-3.0.xm

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:9 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceDB-3.0-27/AceDB-3.0.xml

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:10 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceTimer-3.0-17/AceTimer-3.0.xml

1x Interface/AddOns/LibDFramework-1.0/embeds.xml:11 Couldn't open Interface/AddOns/LibDFramework-1.0/Libs/AceConfig-3.0-3/AceConfig-3.0.xml

**Comment by mrbuds** [comment]
I don't know what LibDFramework-1.0 is but it's not LibGetFrame
