### ISSUE TITLE
Improve HealBot compatibility

### ISSUE THREAD

**Issue by davidmarshall15** [mrbuds/LibGetFrame#31]
The following updates to LibGetFrame-1.0.lua will improve Healbot compatibility.

**local defaultFramePriorities**
```
23 -    "^HealBot", -- healbot
23 +    "^HealBot_HealUnit", -- healbot
24 +    "^hbPet_HealUnit", -- healbot
```

**local defaultTargetFrames**
`73 +    "^hbExtra_HealUnit",`

**local defaultFocusFrames**
`103 +    "^hbExtra_HealUnit",`

**local defaultRaidFrames**
```
105 -    "^HealBot",
108 +    "^HealBot_HealUnit",
109 +    "^hbPet_HealUnit",
```

**Comment by mrbuds** [comment]
Sorry for the delay i completely missed the notification for your ticket, the change is merged now, thank you
