### ISSUE TITLE
Attach wa to PlayerFrame

### ISSUE THREAD

**Issue by N6REJ** [mrbuds/LibGetFrame#35]
I can't figure out how to attach a icon group to the players nameplate generically.  I can do it for elvui but not for default
This doesn't work.
```
  local LGF = LibStub("LibGetFrame-1.0")
  local frame = LGF.GetUnitFrame("player" , {ignorePartyFrame = true, ignoreRaidFrame = true})
  return frame
end
```
but this does..
![image](https://github.com/mrbuds/LibGetFrame/assets/1850089/5aed9ad5-12a8-4db6-9244-42b4b259fc0f)

**Comment by mrbuds** [comment]
Default options are visible here https://github.com/mrbuds/LibGetFrame/blob/master/LibGetFrame-1.0.lua#L445 you want to set ignorePlayerFrame to false
