### ISSUE TITLE
Twitch update reporting new version but installing older version.

### ISSUE THREAD

**Issue by j4gg3red** [mrbuds/LibGetFrame#4]
Twitch keeps reporting 1.1.3 is available and installing 1.1.2-2-gdb40eb7-alpha.

**Comment by WildBillUK** [comment]
exact same issue on 2 PC's. Thought it might have been a twitch client issue.

**Comment by InvalidTheory** [comment]
Same issue, although I think Twitch is erroneously reporting it as 1.1.2 and keeps reinstalling 1.1.3.

**Comment by mrbuds** [comment]
fixed last month, both versions had exact same size and twitch bugged
